version: '3.8'

services:
  db:
    build: .
    image: library-db
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
      
